const videos = [
  { title: "Live From Emmet's Place Farewell Episode!", id: "mX912vvfmdo", start: 0, link: true },
  { title: "Our Delight", id: "Pi09gaUbodQ", start: 0, link: true },
  { title: "Emmet's Place Revival: Joshua Redman Ignites the New Era (Ep. 137)", id: "yssRPU9Rv1E", start: 0, link: true },
  { title: "Live From Emmet's Place Vol. 135 - Steve Nelson & Peter Washington", id: "6RMy_kPB6BE", start: 0, link: true },
  { title: "Live From Emmet's Place Vol. 134 - Kurt Elling", id: "PvN_P7NnNkA", start: 0, link: true },
  { title: "Live From Emmet's Place Vol. 133 - Ashlin Parker & Ruben Fox", id: "-NIIILZ0DBU", start: 0, link: true },
  { title: "Live From Emmet's Place Vol. 132 - Georgia Heers", id: "_d3FpoPnMBM", start: 0, link: true },
  { title: "Live From Emmet's Place Vol. 131 - Anat Cohen", id: "Dj5Ifo7dNW8", start: 0, link: true },
  { title: "Re-Stream: Live From Emmet's Place Vol. 71 - Seamus Blake & Troy Roberts", id: "0zhy16PmEyE", start: 0, link: true },
  { title: "Live From Emmet's Place Vol. 130 - Bria Skonberg & Chris Lewis", id: "Z_SSorSgGyc", start: 0, link: true },
  { title: "Re-Stream: Live From Emmet's Place Vol. 104 - Dayna Stephens & Josh Evans", id: "osBii1jrzwA", start: 0, link: true },
  { title: "Emmet's Place Vol. 129 - 5-Year Bash w/ Cyrille Aimée & Morgan James!", id: "2035jVIaLLA", start: 0, link: true },
  { title: "Live From Emmet's Place Vol. 128 - Patrick Bartley", id: "kCdDHwoIL1c", start: 0, link: true },
  { title: "Emmet Cohen Trio w/ Kurt Elling & Sean Jones - Live From Hilton Head", id: "FKlIsL_opBo", start: 0, link: true },
  { title: "Live From Emmet's Place Vol. 127 - Stella Cole & Vuyo Sotashe", id: "MkzbXqWYypQ", start: 0, link: true },
  { title: "Live From Emmet's Place Vol. 126 - Theo Croker, Herlin Riley & Russell Hall", id: "LnyJ13hVn3U", start: 0, link: true },
  { title: "Live From Emmet's Place Vol. 125 - Houston Person 90th Birthday Celebration!", id: "UjLW97I9pc0", start: 0, link: true },
  { title: "Re-Stream: Live From Emmet's Place Vol. 54 - Cyrille Aimée & Dan Wilson", id: "s3SMQyozgJQ", start: 0, link: true },
  { title: "Live From Emmet's Place Vol. 124 - Vibe Provider w/ Tivon Pennicott, Jeremy Pelt & Reuben Rogers", id: "7FughQpMrN0", start: 0, link: true },
  { title: "Live From Emmet's Place Vol. 123 - Stella Cole, Joy Brown, Lucy Y and Tyreek McDole", id: "RD3HNuLHY2Y", start: 0, link: true },
  { title: "Live From Emmet's Place Vol. 122 - James Morrison", id: "fGufGCE9wcM", start: 0, link: true },
  { title: "Live From Emmet's Place Vol. 121 - Rudresh Mahanthappa & Giveton Gelin", id: "IVn3C0qSg3Q", start: 0, link: true },
  { title: "Live From Emmet's Place Vol. 120 - Ekep Nkwelle & Caity Gyorgy", id: "maSqyNy0QMw", start: 0, link: true },
  { title: "Live From Emmet's Place Vol. 119 - New Jazz Underground", id: "q09FAhLhuiE", start: 0, link: true },
  { title: "Live From Emmet's Place Vol. 118 - Nicholas Payton & Joe Dyson", id: "1OwwN91kEKU", start: 0, link: true },
  { title: "Re-Stream: Emmet Cohen Trio w/ Tootie Heath | Live In New Mexico (2022)", id: "wgAkz3uM-pM", start: 0, link: true },
  { title: "Emmet Cohen Trio - Live at SMOKE (March 2024)", id: "DnihHCUKiGY", start: 0, link: true },
  { title: "Re-Stream: Live From Emmet's Place Vol. 100 - Sean Jones & Tivon Pennicott | Uptown In Orbit Release", id: "UiqRg1i4ELA", start: 0, link: true },
  { title: "Re-Stream: Live From Emmet's Place Vol. 88 - Johnny O'Neal & Ruben Fox", id: "4MQY-ZlU15Q", start: 0, link: true },
  { title: "Live From Emmet's Place Vol. 117 - Brian Lynch & Craig Handy", id: "UdxFqMi26Vg", start: 0, link: true },
  { title: "Emmet Cohen Trio w/ Houston Person (Feat. Sean Jones) - Live at Keystone Korner", id: "wTdNn3DsSEE", start: 0, link: true },
  { title: "Live From Emmet's Place Vol. 116 - Lew Tabackin", id: "_yo0wxGkkaQ", start: 0, link: true },
  { title: "Re-Stream: Live From Emmet's Place Vol. 98 - Buster Williams, Lenny White & Wallace Roney Jr.", id: "ZvvuLMN8O5o", start: 0, link: true },
  { title: "Emmet's Place Miami LIVE 2024 w/ Special Guests", id: "eSl8M3J6_50", start: 0, link: true },
  { title: "Re-Stream: Live From Emmet's Place Vol. 82 - Cedar Walton Birthday Tribute feat. Joe Farnsworth", id: "vfYYfd_MYX0", start: 0, link: true },
  { title: "Re-Stream: Live From Emmet's Place Vol. 97 - Patrick Bartley", id: "QMGhsQ91VHo", start: 0, link: true },
  { title: "Live From Emmet's Place Vol. 115 - Johnny O'Neal, Philip Harper & Brad Mehldau", id: "-5ea4V1T6ag", start: 0, link: true },
  { title: "Best of Emmet Cohen Live in 2023!", id: "6JcLhnLd1zg", start: 0, link: true },
  { title: "Live From Emmet's Place Vol. 114 - Holiday Show Hosted by Matt Wilson", id: "LplJsNyWaIY", start: 0, link: true },
  { title: "Best of Live From Emmet's Place 2023!", id: "B0lZ3LV7okI", start: 0, link: true },
  { title: "Re-Stream: Live From Emmet's Place Vol. 29 feat. Mark Whitfield", id: "LCAUDrtAQDg", start: 0, link: true },
  { title: "Emmet Cohen w/ Benny Benack & J Hoard - Live in Buc Bel Air!", id: "djeiI8Mqzt8", start: 0, link: true },
  { title: "Live From Emmet's Place Vol. 113 - Herlin Riley", id: "HZK2blf-wvI", start: 0, link: true },
  { title: "Emmet Cohen & Houston Person Duo Concert and Interview at WBGO Studios", id: "ds2ksXkQ3OA", start: 0, link: true },
  { title: "Re-Stream: Live From Emmet's Place Vol. 84 - Alphonso Horne & The Gotham Kings", id: "h0FXs33vhTM", start: 0, link: true },
  { title: "Re-Stream: Emmet Cohen Trio Live from Basel, Switzerland", id: "govvSgoC6Eo", start: 0, link: true },
  { title: "Re-Stream: Emmet Cohen Trio Live in Paris | Le Duc des Lombards", id: "6hqGlTHypGw", start: 0, link: true },
  { title: "Emmet Cohen Trio Featuring Tootie Heath - Live in New Mexico 2023", id: "647E_8qnoc8", start: 0, link: true },
  { title: "Live From Emmet's Place Vol. 112 - Tierney Sutton", id: "_V6of0gjK_8", start: 0, link: true },
  { title: "Re-Stream: Live From Emmet's Place Vol. 90 - Gilad Hekselman & Obed Calvaire", id: "0IGljqgyuaw", start: 0, link: true },
  { title: "Emmet Cohen Trio feat. Houston Person - Live at Birdland 2023", id: "7RdKw8FWI2A", start: 0, link: true },
  { title: "Live From Emmet's Place Vol. 111 - Jeremy Pelt", id: "fbv8yp9mEHc", start: 0, link: true },
  { title: "Re-Stream: Emmet Cohen Trio Live from Mexico City", id: "HBhV-B9vmg8", start: 0, link: true },
  { title: "Mary Stallings with Emmet Cohen @ Smoke 2023", id: "wYCVuP3jRKA", start: 0, link: true },
  { title: "Re-Stream: Live From Emmet's Place Vol. 61 - Peter Bernstein", id: "N4wJRb1sRj8", start: 0, link: true },
  { title: "Live From Emmet's Place Vol. 110 - Tyreek McDole, Ekep Nkwelle & Georgia Heers", id: "sgR65tR4VSk", start: 0, link: true },
  { title: "Emmet Cohen Trio feat. Lars Frank & Ola Kvernberg - Live in Molde, Norway", id: "1dZPVq9idIo", start: 0, link: true },
  { title: "Re-Stream: Live From Emmet's Place Vol. 37 - Jazzmeia Horn", id: "J5mja3KHGuU", start: 0, link: true },
  { title: "Live in Funchal, Portugal 2023", id: "OsOOjFhfbE0", start: 0, link: true },
  { title: "Re-Stream: Live From Emmet's Place Vol. 75 - Wycliffe Gordon & Adrian Cunningham", id: "fKiWIuNsaCo", start: 0, link: true },
  { title: "Re-Stream: Presenting the Emmet Cohen Organ Band", id: "a8zR8lXAbrQ", start: 0, link: true },
  { title: "Re-Stream: Live From Emmet's Place Vol. 60 - Pride Celebration!", id: "DaGlqvPd7Q4", start: 0, link: true },
  { title: "Emmet Cohen Trio - Live in Stockholm", id: "HJmQloEgvKk", start: 0, link: true },
  { title: "Live From Emmet's Place Vol. 108 - Terell Stafford, Dick Oatts & Peter Washington", id: "X9rqT3WDbV0", start: 0, link: true },
  { title: "Re-Stream: Live From Emmet's Place Vol. 22 feat. Bruce Harris", id: "2FjYMX_LxKU", start: 0, link: true },
  { title: "Brian Lynch x Emmet Cohen - Miami Live", id: "UfSAbmBLdVM", start: 0, link: true },
  { title: "Live From Emmet's Place Vol. 107 - Patrick Bartley and Larry Grenadier", id: "xxsvf7jDnLQ", start: 0, link: true },
  { title: "Re-Stream: Live From Emmet's Place Vol. 77 - Alexa Tarantino & Tatum Greenblatt", id: "OhP-CO98jU8", start: 0, link: true },
  { title: "Alex Weitz \"Rule of Thirds\" Album Premiere", id: "P-GWpOBCvBs", start: 0, link: true },
  { title: "Live From Emmet's Place Vol. 106 - The Four Freshmen", id: "T10ZkqoP0K8", start: 0, link: true },
  { title: "Re-Stream: Live From Emmet's Place Vol. 83 - Ruben Fox & Benny Benack III", id: "998NpOvfpOM", start: 0, link: true },
  { title: "Emmet Cohen Trio Live At The Jazz Kitchen", id: "j9p9MT34PSY", start: 0, link: true },
  { title: "Emmet Cohen Trio & Friends at The LIED Center in Kansas", id: "Bx9xILeC-mY", start: 0, link: true },
  { title: "Live From Emmet's Place Vol. 105 - Kurt Rosenwinkel", id: "Pe8VP054kKE", start: 0, link: true },
  { title: "Re-Stream: Live From Emmet's Place Vol. 12 - Veronica Swift", id: "geeKBzGSJOw", start: 0, link: true },
  { title: "Emmet Cohen Trio Live at SMOKE Vol. 1", id: "vjr010UBesI", start: 0, link: true },
  { title: "Live From Emmet's Place Vol. 104 - Dayna Stephens & Josh Evans", id: "KltJU1O-uZY", start: 0, link: true },
  { title: "Emmet Cohen Trio @ Tucson Jazz Fest 2023", id: "zlUr5ZCmKKw", start: 0, link: true },
  { title: "Emmet Cohen Trio | Live in Jeonju-si, Korea", id: "_uIe6mWq31k", start: 0, link: true },
  { title: "Re-Stream: Live From Emmet's Place Vol. 39 - Patrick Bartley and Giveton Gelin", id: "TphEUfb1hsg", start: 0, link: true },
  { title: "Emmet Cohen Trio | Detroit Jazz Festival 2022", id: "Yl8lDVh32Fc", start: 0, link: true },
  { title: "Re-Stream: Live From Emmet's Place Vol. 73 - Regina Carter", id: "qO9mrrGPYmg", start: 0, link: true },
  { title: "Live From Emmet's Place Vol. 103 - Paquito D'Rivera & Diego Urcola", id: "17436aZoaHQ", start: 0, link: true },
  { title: "Emmet Cohen & Friends WNYC Holiday Show", id: "8-ckaI4VNCE", start: 0, link: true },
  { title: "Emmet's Place Education: Dan Wilson", id: "6D-ea0calAQ", start: 0, link: true },
  { title: "Live From Emmet's Place Vol. 102 - The Baylor Project", id: "bpJCbUPVAg8", start: 0, link: true },
  { title: "Re-Stream: Live From Emmet's Place Vol. 34 - Warren Wolf", id: "pLqk3-co4SQ", start: 0, link: true },
  { title: "Live From Emmet's Place Vol. 101 - Gabrielle Cavassa & Saul Rubin", id: "pYYoMfx-dxI", start: 0, link: true },
  { title: "Re-Stream: Live From Emmet's Place Vol. 69 - Joel Ross", id: "uQpRTGyGCrA", start: 0, link: true },
  { title: "Emmet Cohen Trio - Live in Lithuania (SECOND SET)", id: "NHeVaBVXZeA", start: 0, link: true },
  { title: "Emmet Cohen Trio - Live in Lithuania", id: "00mDnP2Xkcw", start: 0, link: true },
  { title: "Re-Stream: Live From Emmet's Place Vol. 38 - Martina DaSilva & Lucas Pino", id: "Svm5JRLQqHE", start: 0, link: true },
  { title: "Live From Emmet's Place Vol. 100 - Sean Jones & Tivon Pennicott | Uptown In Orbit Release", id: "UypKGdjMZY4", start: 0, link: true },
  { title: "Live From Emmet's Place Compilation - Johnny O'Neal, Lucy Yeghiazaryan and Mary Stallings", id: "yYmo4BIawe8", start: 0, link: true },
  { title: "Emmet's Place Education: Grant Stewart", id: "a_zvBpmhzzg", start: 0, link: true },
  { title: "Emmet Cohen Trio - Live in Half Moon Bay | SECOND SET", id: "25o99D2uml8", start: 0, link: true },
  { title: "Emmet Cohen Trio - Live in Half Moon Bay | FIRST SET", id: "Htw0UKnm8XU", start: 0, link: true },
  { title: "Re-Stream: Live From Emmet's Place Vol. 51 - Jerry Weldon and Joe Magnarelli", id: "S-s0pU61QWw", start: 0, link: true },
  { title: "Emmet's Place Education: Alexa Tarantino", id: "-o-QcuTt0EU", start: 0, link: true },
  { title: "Live From Emmet's Place Vol. 99 - Joy Brown & Abdias Armenteros", id: "cg5I72fo3-w", start: 0, link: true },
  { title: "Emmet Cohen Trio - Live in Poland", id: "y3_vSIAjBvk", start: 0, link: true },
  { title: "Live From Emmet's Place Vol. 98 - Buster Williams, Lenny White & Wallace Roney Jr.", id: "3AuKLyDcgvA", start: 0, link: true },
  { title: "Live From Emmet's Place Vol. 97 - Patrick Bartley", id: "rGPwPKyij40", start: 0, link: true },
  { title: "Live From Emmet's Place Vol. 96 - Todd Barkan's Keystone Korner 50th Anniversary", id: "F1SOw5f5c_U", start: 0, link: true },
  { title: "Emmet's Place Education: Bruce Harris", id: "eKfSsFhfx2M", start: 0, link: true },
  { title: "Live From Emmet's Place Vol. 95 - Scott Robinson", id: "wQJycPeEwL4", start: 0, link: true },
  { title: "Live From Emmet's Place Vol. 94 - Mike Rodriguez & John Ellis", id: "8Rq33gHzSeE", start: 0, link: true },
  { title: "Live From Emmet's Place Vol. 93 - Miguel Zenón & Matt Penman", id: "ivbE0RreYmg", start: 0, link: true },
  { title: "Emmet's Place Education: Chad Lefkowitz-Brown", id: "Uhpyjud40fo", start: 0, link: true },
  { title: "Emmet Cohen Trio Live from Baroque Jazz Club, Miami", id: "-h-ok27VKTQ", start: 0, link: true },
  { title: "Live From Emmet's Place Vol. 92 - Bruce Harris & Julian Lee", id: "PjqEBOFOY8E", start: 0, link: true },
  { title: "Live From Emmet's Place Vol. 91 - Dr. Eddie Henderson & Steve Davis", id: "AlXkYMnOb_Q", start: 0, link: true },
  { title: "Live From Emmet's Place Vol. 90 - Gilad Hekselman & Obed Calvaire", id: "kC6TMJw2UOQ", start: 0, link: true },
  { title: "Emmet's Place Education: Benny Benack III", id: "uFeiFz9oqJo", start: 0, link: true },
  { title: "Live From Emmet's Place Vol. 89 - Cyrille Aimée & Wayne Tucker", id: "L3nwB1m0TrQ", start: 0, link: true },
  { title: "Live From Emmet's Place Vol. 88 - Johnny O'Neal & Ruben Fox", id: "6g4Qz5PMxDw", start: 0, link: true },
  { title: "Live From Emmet's Place Vol. 87 - Ukraine Benefit (Jazz4Ukraine)", id: "Err1S4ETPh4", start: 0, link: true },
  { title: "Live From Emmet's Place Vol. 86 - Lucy Yeghiazaryan feat. Joe Farnsworth", id: "AnCHAAh_2e8", start: 0, link: true },
  { title: "Live From Emmet's Place Vol. 85 - Victor Lewis, Ben Wolfe, & Stacy Dillard", id: "KZW2QjcXZdw", start: 0, link: true },
  { title: "Live From Emmet's Place Vol. 84 - Alphonso Horne & The Gotham Kings", id: "9TJ22uzBqIY", start: 0, link: true },
  { title: "Emmet Cohen Trio Live at the Dirty Dog Jazz Cafe (Set 2)", id: "RETbpu1VBKg", start: 0, link: true },
  { title: "Emmet Cohen Trio Live at Budapest Jazz Club", id: "cHfRl3Mf6jw", start: 0, link: true },
  { title: "Live From Emmet's Place Vol. 83 - Ruben Fox & Benny Benack III", id: "C3j6fHyR3C8", start: 0, link: true },
  { title: "Emmet's Place Education: Cyrille Aimée", id: "ZqEwsosTu4E", start: 0, link: true },
  { title: "Live From Emmet's Place Vol. 82 - Cedar Walton Birthday Tribute feat. Joe Farnsworth", id: "09SVW38lFyk", start: 0, link: true },
  { title: "Live From Emmet's Place Vol. 81 - Sheila Jordan", id: "XcsiPiDoaK8", start: 0, link: true },
  { title: "Live From Emmet's Place Vol. 80 - Brianna Thomas", id: "WREzEuMMq1c", start: 0, link: true },
  { title: "Emmet's Place Education: Patrick Bartley", id: "-dDZcB1wdZk", start: 0, link: true },
  { title: "Live From Emmet's Place Vol. 79 - Vuyo Sotashe, Grant Stewart, Tyler Mitchell & Evan Sherman", id: "QHZ6kQQi9qo", start: 0, link: true },
  { title: "Live From Emmet's Place Vol. 78 - Mary Stallings", id: "LkiU055Tz7c", start: 0, link: true },
  { title: "Emmet's Place Education: Emmet Cohen Trio (Russell Hall & Kyle Poole)", id: "PfOmAUfJhPk", start: 0, link: true },
  { title: "Live From Emmet's Place Vol. 76 - Randy Brecker & Chad LB", id: "hL1JiZeJ1wA", start: 0, link: true },
  { title: "Live From Emmet's Place Vol. 75 - Wycliffe Gordon & Adrian Cunningham", id: "n6XWDErLPZY", start: 0, link: true },
  { title: "Emmet Cohen w/ Patrick Bartley Live at Twin Cities Jazz Fest", id: "4JfKenSm-tQ", start: 0, link: true },
  { title: "Emmet Cohen Trio Live at the Dirty Dog Jazz Cafe", id: "jZaol3Ox3k4", start: 0, link: true },
  { title: "Live From Emmet's Place Vol. 74 - Jon-Erik Kellso & Evan Christopher", id: "Fl34-PEByqQ", start: 0, link: true },
  { title: "Live From Emmet's Place Vol. 73 - Regina Carter", id: "TlJBfTAynQI", start: 0, link: true },
  { title: "Emmet Cohen Trio Live in Paris | Le Duc des Lombards", id: "tLn7LwhylZo", start: 0, link: true },
  { title: "Live From Emmet's Place Vol. 72 - Dizzy Celebration feat. Bruce Harris & Benny Benack III", id: "UXxKf9w96wc", start: 0, link: true },
  { title: "Emmet Cohen Trio Live at Dazzle Denver", id: "JqdIoQgOGnw", start: 0, link: true },
  { title: "Live From Emmet's Place Vol. 71 - Seamus Blake & Troy Roberts", id: "cmnJY19OMXE", start: 0, link: true },
  { title: "Live From Emmet's Place Vol. 70 - Jeffery Miller, Julian Lee, & Anthony Hervey", id: "tSQOpY4c9ew", start: 0, link: true },
  { title: "Live From Emmet's Place Vol. 69 - Joel Ross", id: "0sw0gBHWqsA", start: 0, link: true },
  { title: "Emmet Cohen Trio at Jazzclub Unterfahrt", id: "CqUVxuIyhHU", start: 0, link: true },
  { title: "Live From Emmet's Place Vol. 68 - Bird at 101", id: "OPt68q8BtaY", start: 0, link: true },
  { title: "Live From Emmet's Place Vol. 67 - Samara Joy", id: "CGkndZKNdTc", start: 0, link: true },
  { title: "Live From Emmet's Place Vol. 66 - Nicholas Payton", id: "7yKGkDHp5oc", start: 0, link: true },
  { title: "Live From Emmet's Place Vol. 65 - Russell Malone", id: "Rdcgz0Qwquo", start: 0, link: true },
  { title: "Live From Emmet's Place Vol. 64 - Eric Alexander & Vincent Herring (Part 1)", id: "K7JbXbIP9VY", start: 0, link: true },
  { title: "Benny Golson w/ the Emmet Cohen Trio Part 1", id: "aCeTgGtnl7U", start: 0, link: true },
  { title: "Presenting the Emmet Cohen Organ Band", id: "puH9fjniSP4", start: 0, link: true },
  { title: "Live From Emmet's Place Vol. 63 - Christian McBride", id: "IzOfzEAQ9rA", start: 0, link: true },
  { title: "Live From Emmet's Place Vol. 62 - Sean Jones", id: "OTL3LkKueho", start: 0, link: true },
  { title: "Live From Emmet's Place Vol. 61 - Peter Bernstein", id: "hVKAYDZoMHQ", start: 0, link: true },
  { title: "Live From Emmet's Place Vol. 60 - Pride Celebration!", id: "66a_YiIvOIg", start: 0, link: true },
  { title: "Live From Emmet's Place Vol. 59 - Houston Person", id: "zcx5Z0RegEU", start: 0, link: true },
  { title: "Live From Emmet's Place Vol. 58 - Pasquale Grasso & Spike Wilner", id: "hzYYhDFTlfg", start: 0, link: true },
  { title: "Live From Emmet's Place Vol. 57 - Emmet's Birthday feat. Michael Stephenson & Benny Benack III", id: "1vp_7J6rzX4", start: 0, link: true },
  { title: "Live From Emmet's Place Vol. 56 - Joe Lovano", id: "bjbUYSG1Ha4", start: 0, link: true },
  { title: "Live From Emmet's Place Vol. 55 - Camille Thurman", id: "9JG7IZTqP7I", start: 0, link: true },
  { title: "Live From Emmet's Place Vol. 54 - Cyrille Aimée & Dan Wilson", id: "ha-oS6BC8TU", start: 0, link: true },
  { title: "Live From Emmet's Place Vol. 53 - Warren Vache & Harry Allen", id: "lsBMRcFufpQ", start: 0, link: true },
  { title: "Live From Emmet's Place Vol. 52 - Patrick Bartley and Bruce Harris", id: "_hQUHEBFfys", start: 0, link: true },
  { title: "Live From Emmet's Place Vol. 51 - Jerry Weldon and Joe Magnarelli", id: "dQQFzF8rg-k", start: 0, link: true },
  { title: "Live From Emmet's Place Vol. 50 - Lucy Yeghiazaryan & Grant Stewart", id: "IUpaQR94q88", start: 0, link: true },
  { title: "Live From Emmet's Place Vol. 49 - Vanisha Gould, Roxy Coss, Mariel Bildsten, & Liya Grigoryan", id: "_l3kMDFUm0w", start: 0, link: true },
  { title: "Emmet Cohen WBGO Spotlight!", id: "jlM0jR4OGnk", start: 0, link: true },
  { title: "Live From Emmet's Place Vol. 48 - Sasha Berliner & Nicole Glover", id: "gOqHHAemAWA", start: 0, link: true },
  { title: "Emmet Cohen Trio and Guests Live from Moscow, Russia", id: "q5SwTPZLM5o", start: 0, link: true },
  { title: "Live From Emmet's Place Vol. 47 - Houston Person", id: "efAMMyvsNSE", start: 0, link: true },
  { title: "Live From Emmet's Place Vol. 46 - Samara Joy", id: "9WujhHcQh8k", start: 0, link: true },
  { title: "Live From Emmet's Place Vol. 45 - Frank Lacy & Stacy Dillard", id: "to82gPlgh98", start: 0, link: true },
  { title: "Live From Emmet's Place Vol. 44 - Lezlie Harrison, Allan Harris, & Bruce Harris", id: "9KWn9TdRsbI", start: 0, link: true },
  { title: "Valentine's Day: Emmet Cohen Quintet Part 2", id: "rQ9ex1PLw8A", start: 0, link: true },
  { title: "Valentine's Day: Emmet Cohen Quintet", id: "wBXlO_g97sc", start: 0, link: true },
  { title: "Live From Emmet's Place Vol. 43 - Veronica Swift & Johnny O'Neal", id: "-tohPcNhUEU", start: 0, link: true },
  { title: "Live From Emmet's Place Vol. 42 - Future Stride Album Release Party", id: "JmyDsVMl5WI", start: 0, link: true },
  { title: "Live From Emmet's Place Vol. 41 - Catherine Russell & Ken Peplowski", id: "PLiRls2DZHo", start: 0, link: true },
  { title: "Emmet Cohen Trio with Special Guest Mark Whitfield", id: "TSVALVU7OJM", start: 0, link: true },
  { title: "Live From Emmet's Place Vol. 40 - Cedar Walton Celebration feat. Joe Farnsworth, Mathis, Julius", id: "ZKk3sidSlwU", start: 0, link: true },
  { title: "Live From Emmet's Place Vol. 39 - Giveton Gelin & Patrick Bartley", id: "j2CfeMwxtlY", start: 0, link: true },
  { title: "Live From Emmet's Place Vol. 38 - Martina DaSilva & Lucas Pino", id: "GmAP5ATFEmw", start: 0, link: true },
  { title: "Live From Emmet's Place Vol. 37 - Jazzmeia Horn", id: "XyjwSKtlQcY", start: 0, link: true },
  { title: "Live From Emmet's Place Vol. 36 - Vuyo Sotashe, Bruce Harris & Godwin Louis", id: "sB4evPCigXc", start: 0, link: true },
  { title: "Live From Emmet's Place Vol. 34 - Warren Wolf", id: "mNBOwRj4Bnk", start: 0, link: true },
  { title: "Live From Emmet's Place Vol. 33 - Cyrille Aimée and Armand Hirsch", id: "OC-TbR3qYLk", start: 0, link: true },
  { title: "Live From Emmet's Place Vol. 32 - Benny Benack III 30th Birthday Celebration!", id: "-Pm-t1SAtXM", start: 0, link: true },
  { title: "Live From Emmet's Place Vol. 31 feat. Veronica Swift and Jerry Weldon", id: "dK6x8NSD098", start: 0, link: true },
  { title: "Live From Emmet's Place Vol. 30 feat. Vuyo Sotashe", id: "JSblll8Lzfo", start: 0, link: true },
  { title: "Emmet Cohen Trio Live from Cologne, Germany 2020", id: "75hYNUp5Gus", start: 0, link: true },
  { title: "Live From Emmet's Place Vol. 29 feat. Mark Whitfield", id: "5aGwqiFNyjU", start: 0, link: true },
  { title: "Live From Emmet's Place Vol. 28 feat. Bruce Harris and Patrick Bartley- Dizzy's Business!", id: "aiYB4c9b1SM", start: 0, link: true },
  { title: "Emmet Cohen Trio Live from Basel, Switzerland", id: "fnOePu44NLM", start: 0, link: true },
  { title: "Emmet Cohen Trio Live at Umbria Jazz in Perugia Italy!", id: "HhO15RqwAho", start: 0, link: true },
  { title: "Live From Emmet's Place Vol. 27 (Bud Powell Celebration)", id: "-vrQWBnK6do", start: 0, link: true },
  { title: "Live From Emmet's Place Vol. 26 ft. Godwin Louis", id: "2CTGlTg2gKQ", start: 0, link: true },
  { title: "Live From Emmet's Place Vol. 25 ft. Johnny O'Neal and Stacy Dillard", id: "dH4dRWz7ALI", start: 0, link: true },
  { title: "Live From Emmet's Place Vol. 24 feat. Tivon Pennicott", id: "M-ymzK-4E0U", start: 0, link: true },
  { title: "Live From Emmet's Place Vol. 23", id: "4dwnQ4IqfQQ", start: 0, link: true },
  { title: "Live From Emmet's Place Vol. 22 feat. Bruce Harris", id: "xe8mYGFUUxI", start: 0, link: true },
  { title: "Live at Emmet's Place Vol. 21 feat. Michela Lerman", id: "Kg_2meKjm7U", start: 0, link: true },
  { title: "Live at Emmet's Place Vol. 20", id: "3CF31HIUCqs", start: 0, link: true },
  { title: "Live at Emmet's Place Vol. 19 featuring Cyrille Aimée", id: "kR3nm6gA05c", start: 0, link: true },
  { title: "Live at Emmet's Place Vol. 18", id: "x-r7uR962i0", start: 0, link: true },
  { title: "Live at Emmet's Place Vol. 17", id: "Od6EdUzDX1g", start: 0, link: true },
  { title: "Live at Emmet's Place Vol. 16 feat. Patrick Bartley", id: "j4jEh5i32IM", start: 0, link: true },
  { title: "Live at Emmet's Place Vol. 15", id: "AwLcq8PBUzU", start: 0, link: true },
  { title: "Live at Emmet's Place Vol. 14 feat. Johnny O'Neal", id: "EXk1SsfkZNM", start: 0, link: true },
  { title: "Live at Emmet's Place Vol. 13", id: "0OVwegcgris", start: 0, link: true },
  { title: "Live at Emmet's Place Vol. 12 feat Veronica Swift", id: "KgMiSA_ZlZg", start: 0, link: true },
  { title: "Live at Emmet's Place Vol. 11", id: "JJPT0LKySZ4", start: 0, link: true },
  { title: "Live at Emmet's Place Vol. 10", id: "dIl1UhkHx3M", start: 0, link: true },
  { title: "Live at Emmet's Place Vol. 9", id: "zgqf3h_N4l8", start: 0, link: true },
  { title: "5/14 Livestream for St. Cecilia Music Center", id: "tERCZeazYWk", start: 0, link: true },
  { title: "Live at Emmet's Place Vol. 8", id: "gL9EH5usAuU", start: 0, link: true },
  { title: "Live at Emmet's Place Vol. 7", id: "K5u6LL-Nvr4", start: 0, link: true },
  { title: "Live at Emmet's Place Vol. 6", id: "kVuCykKQbGk", start: 0, link: true },
  { title: "Live at Emmet's Place Vol. 6", id: "dj_bEo_8QYo", start: 0, link: true },
  { title: "Live from Emmet's Vol. 5", id: "_iW1MSSNUds", start: 0, link: true },
  { title: "Live From Emmet's Place Vol. 3", id: "RpOqwLovRm0", start: 0, link: true },
];
